[package]
name = "rscap"
authors = ["Nathaniel Bennett <me[at]nathanielbennett[dotcom]>"]
description = "Rust packet capture and manipulation utilities"
rust-version = "1.65" # GATs stabilized in this version; required for `pkts`
version = "0.1.2"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/pkts-rs/rscap"

[features]
default = ["std"]
std = ["alloc"]
alloc = []
libcfull = []

[dependencies]
bitflags = { version = "2.6.0" }
libc = { version = "0.2" }
#pkts = { version = "0.1", path = "../pkts" }
pkts-common = { version = "0.1.3", path = "../pkts-common" }
