[package]
name = "pkts"
rust-version = "1.65" # GATs stabilized in this version; required for `Sequence` types
version = "0.1.0"
edition = "2021"

[features]
default = ["std", "custom_layer_selection"]
std = ["alloc"]
alloc = []
custom_layer_selection = ["rscap-macros/custom_layer_selection"]

[dependencies]
rscap-macros = { path = "../../rscap-macros", version = "0.1" }
